name: Bazel
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  check_lints:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Check format
      run: ./format.sh

  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build everything
      run: ./bazel build //...

    - name: Run tests
      run: ./bazel test //...